export const colorsEnums = {
	ring: 'ring',
	card: 'card',
	muted: 'muted',
	input: 'input',
	accent: 'accent',
	border: 'border',
	primary: 'primary',
	popover: 'popover',
	secondary: 'secondary',
	background: 'background',
	foreground: 'foreground',
	destructive: 'destructive',
	cardForeground: 'cardForeground',
	mutedForeground: 'mutedForeground',
	accentForeground: 'accentForeground',
	popoverForeground: 'popoverForeground',
	primaryForeground: 'primaryForeground',
	secondaryForeground: 'secondaryForeground',
	destructiveForeground: 'destructiveForeground',
};
